### ISSUE TITLE
Throttle if error code?

### ISSUE THREAD

**Issue by vacumet** [JohnLindahlTech/pass-bokning#4]
After running every minute this morning i got this message:

2022-03-23T08:22:40+01:00 Du har gjort för många 'första lediga tid' sökningar, var vänlig och vänta en stund.
 200
2022-03-23T08:22:40+01:00 Error: Post was not a redirect
    at file:///home/banana/pass/pass-bokning-main/src/main.mjs:33:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pickTime (file:///home/banana/pass/pass-bokning-main/src/flow/5.pickTime.mjs:37:16)
    at async main (file:///home/banana/pass/pass-bokning-main/src/main.mjs:76:27)
    at async watchMain (file:///home/banana/pass/pass-bokning-main/src/entry.mjs:56:17)
    at async entry (file:///home/banana/pass/pass-bokning-main/src/entry.mjs:89:20) {
  statusCode: 418
}

I changed the source IP for my request and changed to every 3 minutes. A throttle feature would be nice :)

**Comment by JohnLindahlTech** [comment]
My experience is that once I get this error, it is there for about 2 calls and then resumes.

Also look into the the `--timeout` flag for running the script which does just that but on the "global" level.

But you are correct that I have not implemented an exponential callback on the very recursive function of finding a time-slot. Feel free to provide a PR if you find the need.
